### PR TITLE
Do not flush metrics queue if queue is empty

### LINKED ISSUE #301: App Hangs when MetricsManager is disabled and exception is thrown
### Repro Project
[TestHockeyApp.NativeiOS.zip](https://github.com/bitstadium/HockeySDK-iOS/files/301795/TestHockeyApp.NativeiOS.zip)

### Repro Steps
1. Start app
2. Press 'Throw Exception'
3. Verify app hangs

### Notes
Occurs when MetricsManager is disabled before the manager is started:
```
    [[BITHockeyManager sharedHockeyManager] configureWithIdentifier:@"Your-App-Id"];
    [[BITHockeyManager sharedHockeyManager] setDisableMetricsManager:YES];
    [[BITHockeyManager sharedHockeyManager] startManager];
```

### PR DESCRIPTION
**Pull request by chrwend**
Fixes #301: App freezes when metrics module is disabled and exception is thrown.

### CODE REVIEW

File: Classes/BITCrashManager.m [hunk 1]
```diff
@@ -99,6 +99,12 @@
 
 #if HOCKEYSDK_FEATURE_METRICS
 static void bit_save_events_callback(siginfo_t *info, ucontext_t *uap, void *context) {
+  
+  // Do not flush metrics queue if queue is empty (metrics module disabled) to not freeze the app
+  if(!BITSafeJsonEventsString) {
```
Comment (lumaxis) [inline Classes/BITCrashManager.m]: Add a space after `if`? :)

**Comment by lumaxis** [comment]
👌
