### PR TITLE
Remove unnecessary calls to -[NSUserDefaults synchronize]

### LINKED ISSUE #188: `synchronize` is generally considered bad practice
Synchronize is periodically invoked automatically so it rarely needs to be called manually. It is generally considered excessive to call it manually. 

screen shot 2015-08-20 at 14 52 42

I get it if the app is crashing and you need to ensure user defaults is synchronized, but is this IO really necessary in all cases? You are assuming the user defaults for any application using HockeyApp is quite lightweight, which may or may not be true.

### PR DESCRIPTION
**Pull request by lumaxis**
This fixes #188 and also potentially speeds our code up a tiny bit in some places

### CODE REVIEW

File: Classes/BITCrashManager.m [hunk 1]
```diff
@@ -198,9 +198,8 @@ - (instancetype)init {
     
     _crashManagerStatus = BITCrashManagerStatusAlwaysAsk;
     
-    NSString *testValue = [[NSUserDefaults standardUserDefaults] stringForKey:kBITCrashManagerStatus];
-    if (testValue) {
-      _crashManagerStatus = (BITCrashManagerStatus) [[NSUserDefaults standardUserDefaults] integerForKey:kBITCrashManagerStatus];
+    if ([[NSUserDefaults standardUserDefaults] stringForKey:kBITCrashManagerStatus]) {
+      _crashManagerStatus = (BITCrashManagerStatus)[[NSUserDefaults standardUserDefaults] integerForKey:kBITCrashManagerStatus];
```
Comment (lumaxis) [inline Classes/BITCrashManager.m]: @chrwend I switched this back from using `valueForKey:` to `stringForKey:`. `valueForKey:` is a Key-Value Coding method that could have other side effects.
The actual value is an integer but we can't use `integerForKey:` in the `if (…)` condition because it can't return `nil`, only `0` which might be an actually valid value. Therefore we have to use two different methods for checking if the value exists and then actually getting it.
